### PR TITLE
openMenuOffset default value setted up via props

### PR DESCRIPTION
**Pull request by xxsnakerxx**

### CODE REVIEW

**Comment by xxsnakerxx** [comment]
@Kureev why it was closed? What's wrong?

**Comment by Kureev** [comment]
@xxsnakerxx Damn, I tough I've already merged it in, sorry. 
It's just hard to manage PRs not related to any story and without any description. You can find a nice article about ["How to write the perfect PR"](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)

**Comment by Kureev** [comment]
I can't merge it in due to conflicts. I'll manually pick up your changes and push it as a patched version

**Comment by Kureev** [comment]
Added in `0.15.5`

**Pull request closed without merging**
